# Use an official Node image as base
FROM node:22-alpine

WORKDIR /app

# Install development dependencies
RUN apk add --no-cache \
    git \
    curl

# Change ownership to node user
# RUN chown -R node:node /app
# USER node

# Copy package.json and install dependencies
COPY package.json .
RUN npm install

COPY . .
# No need to COPY . . as we'll use volume mounting
EXPOSE 3000
# Expose React DevTools port
EXPOSE 8097

# Run the development server with hot reload
CMD ["npm", "run", "dev"]