FROM golang:1.24-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache \
    git \
    curl \
    make \
    gcc \
    libc-dev

# Copy go.mod and go.sum
COPY go.mod ./
COPY .env ./

# Download dependencies
RUN go mod download

# Copy the rest of the application
COPY . .

# Expose port
EXPOSE 8080

# Run the application
CMD ["go", "run", "-mod=mod", "cmd/api/main.go"]
